version: "3.7"

services:
  #view the frontend from localhost:3001
  web:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - 3001:80
      - 8080:80
    networks: 
      - backend_network
  backend:
    build:
      context: .
      dockerfile: node.dockerfile
    working_dir: /var/www
    ports:
      - 3000:3000
    networks: 
      - backend_network
networks: 
  backend_network:
    driver: bridge
