apiVersion: v1
kind: Service
metadata:
  name: button.js
#  labels:
#    name: new-website
spec: 
  ports:
    - port: 80 
      targetPort: 3001        
      protocol: TCP
  selector:
    app: button.js
  type: LoadBalancer