apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: gcr.io/fast-gke/button.js
    #  jib: {}
    # Use Jib if you don't have dockerfile.
#metadata:
#  name: new-website
deploy:
  kubectl:
    manifests:
    - k8s-deployment.yml
    - k8s-service.yml
profiles:
   - name: cloud-build
     build:
       googleCloudBuild: {}  